version: '3.8'

services:
  front:
    build:
      context: ./.docker/front
      dockerfile: Dockerfile
    container_name: front
    environment:
      - NODE_ENV=development
    volumes:
      - ./front:/app:cached
    # command: sh -c 'cd front'
    ports:
      - '3000:3000'
    tty: true
