version: '3.8'

services:
  front:
    build:
      context: ./.docker/front
      dockerfile: Dockerfile
    image: front
    container_name: front
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/app:cached
    ports:
      - '3000:3000'
    tty: true

  db:
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    image: db
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hoge
      MYSQL_USER: hoge
      MYSQL_PASSWORD: hgoe
      MYSQL_ROOT_PASSWORD: hoge
      TZ: "Asia/Tokyo"
    volumes:
      - db_volumes:/var/lib/mysql:cached

  api:
    build:
      context: ./.docker/api
      dockerfile: Dockerfile
    image: api
    container_name: api
    volumes:
      - ./api:/app:cached
    tty: true
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
    depends_on:
      - db

volumes:
  db_volumes:
